# use Delegate_facts to get Server ip_address
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_delegation.html#delegating-facts

- name: Gather facts from Apt_cacher server
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['apt_cacher_server'] }}"
  when: not ansible_user_id == "vagrant"

# - debug:
#     var: hostvars['apt_cacher_server0']['ansible_default_ipv4']['address']

# - debug:
#     msg: "{{ groups['apt_cacher_server'][0]['ansible_default_ipv4'] }}"

- name: Default node on lan (bare metal or virtual)
  ansible.builtin.set_fact:
    aptcacher_server: "{{ groups['apt_cacher_server'][0] }}"
  when: not ansible_user_id == "vagrant"
  notify: Reload systemd to pickup apt changes

- name: Vagrant host
  ansible.builtin.set_fact:
    aptcacher_server: "{{ ansible_default_ipv4.gateway }}"
  when: ansible_user_id == "vagrant" and ansible_virtualization_role == "guest"
  notify: Reload systemd to pickup apt changes

- name: Custom Libvirt host
  ansible.builtin.set_fact:
    aptcacher_server: "{{ ansible_default_ipv4.gateway }}"
  when: cache_on_virt_host and ansible_default_ipv4.gateway == "192.168.122.1" and ansible_virtualization_role == "guest"
  notify: Reload systemd to pickup apt changes