---
# Solution: https://forum.qubes-os.org/t/trouble-setting-up-apt-cacher-ng/12223
- name: Fix, 403 CONNECT denied error
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "sed -i 's#https://#http://HTTPS///#g' /etc/apt/sources.list"
    - "sed -i 's#https://#http://HTTPS///#g' /etc/apt/sources.list.d/*.list"
  become: true
  failed_when: false

- name: apt update cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

# from: Apt update
#Warning: The unit file, source configuration file or drop-ins of apt-news.service changed on disk. Run 'systemctl daemon-reload' to reload units.
#Warning: The unit file, source configuration file or drop-ins of esm-cache.service changed on disk. Run 'systemctl daemon-reload' to reload units.
- name: Reload systemd to pickup apt changes
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true